# Generated by Django 4.0.4 on 2022-08-05 12:27

from django.db import migrations, models
import django.db.models.deletion
import teacher.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('department', models.CharField(max_length=8, verbose_name='بخش')),
                ('about', models.TextField(blank=True, null=True, verbose_name='درباره')),
                ('image', models.ImageField(blank=True, upload_to='images/teachers/', validators=[teacher.validators.image_size_validator], verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='لینک')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='teacher.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'لینک',
                'verbose_name_plural': 'لینک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='teacher.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل\u200cها',
            },
        ),
    ]
