# Generated by Django 4.0.4 on 2022-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='CSE', max_length=8, verbose_name='بخش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره'),
        ),
    ]
