# Generated by Django 4.0.3 on 2022-04-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teacher', '0002_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='teacheritem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_items', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='teacheritem',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_items', to='teacher.teacher'),
        ),
    ]
