# Generated by Django 4.0.4 on 2022-05-05 22:23

from django.db import migrations, models
import gdstorage.storage
import teacher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/teachers/', validators=[teacher.validators.image_size_validator], verbose_name='تصویر'),
        ),
    ]
