# Generated by Django 4.0.4 on 2022-06-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teacher', '0004_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='teacher.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='teacher.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='teacheritem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_items', to='contenttypes.contenttype', verbose_name='نوع محتوا'),
        ),
        migrations.AlterField(
            model_name='teacheritem',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_items', to='teacher.teacher', verbose_name='استاد'),
        ),
    ]
