# Generated by Django 4.0.3 on 2022-04-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_email_email_alter_externallink_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'ایمیل', 'verbose_name_plural': 'ایمیل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'verbose_name': 'لینک', 'verbose_name_plural': 'لینک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AlterModelOptions(
            name='teacheritem',
            options={'verbose_name': 'رابط استاد', 'verbose_name_plural': 'رابط\u200cهای اساتید'},
        ),
    ]
