# Generated by Django 4.0.4 on 2022-04-12 13:59

import course.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='واحد')),
                ('term_in_chart', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], verbose_name='ترم در چارت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('en_title', models.CharField(max_length=255, verbose_name='عنوان به انگلیسی')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='تگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('B', 'پایه'), ('G', 'عمومی'), ('O', 'اختیاری'), ('S', 'تخصصی')], max_length=1, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(course.models.Classroom._current_year)], verbose_name='سال')),
                ('semester', models.CharField(choices=[('FA', 'اول'), ('SP', 'دوم'), ('SU', 'تابستان')], max_length=2, verbose_name='نیم سال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.session', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'گریدر',
                'verbose_name_plural': 'گریدرها',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('url', models.URLField(max_length=255, verbose_name='لینک دانلود')),
                ('type', models.CharField(choices=[('M', 'میانترم'), ('F', 'پایانترم'), ('H', 'تمرین'), ('Q', 'کوییز'), ('O', 'دیگر')], max_length=1, verbose_name='نوع')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.session', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'منبع',
                'verbose_name_plural': 'منابع',
            },
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'هم\u200cنیاز'), ('P', 'پیش\u200cنیاز')], max_length=1, verbose_name='نوع')),
                ('course_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites_from', to='course.course', verbose_name='درس مبدا')),
                ('course_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites_to', to='course.course', verbose_name='درس مقصد')),
            ],
            options={
                'verbose_name': 'نیاز',
                'verbose_name_plural': 'نیازها',
            },
        ),
    ]
