# Generated by Django 4.0.4 on 2022-08-21 14:32

import course.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_alter_author_options_remove_author_reference_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(course.models.Classroom._current_year)], verbose_name='سال')),
                ('semester', models.CharField(choices=[('1', 'اول'), ('2', 'دوم'), ('S', 'تابستان')], max_length=1, verbose_name='نیم سال')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('en_title', models.CharField(max_length=255, verbose_name='عنوان به انگلیسی')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='واحد')),
                ('type', models.CharField(choices=[('B', 'پایه'), ('G', 'عمومی'), ('O', 'اختیاری'), ('S', 'تخصصی')], max_length=1, verbose_name='نوع')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='تگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('references', models.ManyToManyField(blank=True, related_name='courses', to='reference.reference', verbose_name='مراجع')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
            ],
            options={
                'verbose_name': 'گریدر',
                'verbose_name_plural': 'گریدرها',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/resources/', verbose_name='فایل')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('M', 'میانترم'), ('F', 'پایانترم'), ('P', 'پروژه'), ('H', 'تمرین'), ('Q', 'کوییز'), ('O', 'دیگر')], max_length=1, verbose_name='نوع')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('support_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک دانلود حمایتی')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='course.classroom', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'منبع',
                'verbose_name_plural': 'منابع',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='course.course', verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tas',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='course.ta', verbose_name='گریدرها'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='classrooms', to='teacher.teacher', verbose_name='اساتید'),
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'هم\u200cنیاز'), ('P', 'پیش\u200cنیاز')], max_length=1, verbose_name='نوع')),
                ('course_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites_from', to='course.course', verbose_name='درس مبدا')),
                ('course_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites_to', to='course.course', verbose_name='درس مقصد')),
            ],
            options={
                'verbose_name': 'نیاز',
                'verbose_name_plural': 'نیازها',
                'unique_together': {('course_from', 'course_to')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('year', 'semester', 'course')},
        ),
    ]
