# Generated by Django 4.0.4 on 2022-04-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='term_in_chart',
        ),
    ]
