# Generated by Django 4.0.3 on 2022-04-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='course.course'),
            preserve_default=False,
        ),
    ]
