# Generated by Django 4.0.3 on 2022-04-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_session_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisite',
            name='course1',
        ),
        migrations.RemoveField(
            model_name='requisite',
            name='course2',
        ),
        migrations.AddField(
            model_name='requisite',
            name='course_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_from', to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisite',
            name='course_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_to', to='course.course'),
            preserve_default=False,
        ),
    ]
