# Generated by Django 4.0.4 on 2022-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_term_in_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='support_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک دانلود حمایتی'),
        ),
    ]
