# Generated by Django 4.0.3 on 2022-04-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_requisite_course1_remove_requisite_course2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='term_in_chart',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
