# Generated by Django 4.0.4 on 2022-05-05 22:23

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_resource_support_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='files/resources/', verbose_name='فایل'),
        ),
    ]
