# Generated by Django 4.0.3 on 2022-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_term_in_chart_alter_course_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date_modified',
            field=models.DateTimeField(),
        ),
    ]
