# Generated by Django 4.0.3 on 2022-04-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_resource_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisite',
            name='course_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites_from', to='course.course'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='course_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites_to', to='course.course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='course.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='course.course'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tas', to='course.session'),
        ),
    ]
