# Generated by Django 4.0.4 on 2022-06-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_renamed_session_and_its_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='course.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('1', 'اول'), ('2', 'دوم'), ('S', 'تابستان')], max_length=1, verbose_name='نیم سال'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='course.classroom', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tas', to='course.classroom', verbose_name='کلاس'),
        ),
    ]
