# Generated by Django 4.0.4 on 2022-04-11 12:20

import course.models
import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_requisite_course_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_modified',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(course.models.Session._current_year)]),
        ),
    ]
