# Generated by Django 4.0.4 on 2022-06-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_classroom_course_alter_classroom_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('M', 'میانترم'), ('F', 'پایانترم'), ('P', 'پروژه'), ('H', 'تمرین'), ('Q', 'کوییز'), ('O', 'دیگر')], max_length=1, verbose_name='نوع'),
        ),
    ]
