# Generated by Django 4.0.4 on 2022-04-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_resource_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.session'),
        ),
    ]
