# Generated by Django 4.0.4 on 2022-06-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_resource_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('year', 'semester', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='requisite',
            unique_together={('course_from', 'course_to')},
        ),
    ]
