# Generated by Django 4.0.3 on 2022-04-11 14:34

import course.models
import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_resource_session_alter_session_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='en_title',
            field=models.CharField(max_length=255, verbose_name='عنوان به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تگ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='term_in_chart',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], verbose_name='ترم در چارت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('B', 'Basic'), ('G', 'General'), ('O', 'Optional'), ('S', 'Specialized')], max_length=1, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='type',
            field=models.CharField(choices=[('C', 'Corequisite'), ('P', 'Prerequisite')], max_length=1, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_modified',
            field=django_jalali.db.models.jDateTimeField(verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('M', 'Midterm'), ('F', 'Final'), ('H', 'Homework'), ('Q', 'Quiz'), ('O', 'Other')], max_length=1, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=255, verbose_name='لینک دانلود'),
        ),
        migrations.AlterField(
            model_name='session',
            name='semester',
            field=models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('SU', 'Summer')], max_length=2, verbose_name='نیم سال'),
        ),
        migrations.AlterField(
            model_name='session',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(course.models.Session._current_year)], verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
    ]
