# Generated by Django 4.0.3 on 2022-04-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_description_alter_course_en_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'دروس'},
        ),
        migrations.AlterModelOptions(
            name='requisite',
            options={'verbose_name': 'نیاز', 'verbose_name_plural': 'نیازها'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'منبع', 'verbose_name_plural': 'منابع'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ta',
            options={'verbose_name': 'گریدر', 'verbose_name_plural': 'گریدرها'},
        ),
    ]
