# Generated by Django 4.2.4 on 2023-09-17 21:30

import core.helpers
import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', core.models.ShortUuidField(db_index=True, default=core.helpers.uuid_generator, editable=False, max_length=11, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=63, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=63, null=True, verbose_name='Name in English')),
                ('tag', models.CharField(max_length=127, null=True, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', core.models.ShortUuidField(db_index=True, default=core.helpers.uuid_generator, editable=False, max_length=11, unique=True, verbose_name='UUID')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified Time')),
                ('first_name', models.CharField(max_length=63, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=63, null=True, verbose_name='Last Name')),
                ('honorific', models.CharField(max_length=31, null=True, verbose_name='Honorific')),
                ('about', models.TextField(default='', null=True, verbose_name='About')),
                ('tag', models.CharField(max_length=127, null=True, verbose_name='Tag')),
                ('image', models.ImageField(null=True, upload_to='images/professors/', validators=[core.validators.MaxImageSizeValidator(1)], verbose_name='Image')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='professors.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True, verbose_name='Address')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='professors.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
