# Generated by Django 4.2.5 on 2023-10-01 18:57

import core.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='tag',
            field=core.models.TagField(blank=True, max_length=127, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\u0600-ۿ_]*$', 'Tags can only contain Persian and English letters and underscores.')], verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='tag',
            field=core.models.TagField(blank=True, max_length=127, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\u0600-ۿ_]*$', 'Tags can only contain Persian and English letters and underscores.')], verbose_name='Tag'),
        ),
    ]
