# Generated by Django 4.2.5 on 2023-10-02 05:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_department_tag_alter_professor_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/professors', validators=[core.validators.MaxImageSizeValidator(1)], verbose_name='Image'),
        ),
    ]
