# Generated by Django 4.2.5 on 2023-10-02 10:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_alter_professor_about_alter_professor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/professors', validators=[core.validators.MaxImageSizeValidator(5)], verbose_name='Image'),
        ),
    ]
