# Generated by Django 4.0.4 on 2022-08-05 12:27

from django.db import migrations, models
import django.db.models.deletion
import reference.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/references/', verbose_name='فایل')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('support_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک دانلود حمایتی')),
                ('cover_image', models.ImageField(blank=True, upload_to='images/references/', validators=[reference.validators.image_size_validator], verbose_name='تصویر جلد')),
            ],
            options={
                'verbose_name': 'مرجع',
                'verbose_name_plural': 'مراجع',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='reference.reference', verbose_name='مرجع')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده\u200cها',
            },
        ),
    ]
