# Generated by Django 4.0.4 on 2022-04-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, upload_to='img/r/', verbose_name='تصویر جلد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('url', models.URLField(max_length=255, verbose_name='لینک دانلود')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'مرجع',
                'verbose_name_plural': 'مراجع',
            },
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='آی دی آبجکت')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.reference', verbose_name='مرجع')),
            ],
            options={
                'verbose_name': 'رابط مرجع',
                'verbose_name_plural': 'رابط\u200cهای مراجع',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.reference', verbose_name='مرجع')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده\u200cها',
            },
        ),
    ]
