# Generated by Django 4.0.4 on 2022-04-27 22:52

from django.db import migrations, models
import reference.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='img/r/', validators=[reference.validators.image_size_validator], verbose_name='تصویر جلد'),
        ),
    ]
