# Generated by Django 4.0.3 on 2022-04-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_reference_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='img/r/'),
        ),
    ]
