# Generated by Django 4.0.4 on 2022-05-05 22:23

from django.db import migrations, models
import gdstorage.storage
import reference.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_reference_support_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='cover_image',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/references/', validators=[reference.validators.image_size_validator], verbose_name='تصویر جلد'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='files/references/', verbose_name='فایل'),
        ),
    ]
