# Generated by Django 4.0.4 on 2022-04-11 12:20

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_alter_author_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='date_modified',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
