# Generated by Django 4.0.4 on 2022-06-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reference', '0004_alter_reference_cover_image_alter_reference_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='reference.reference', verbose_name='مرجع'),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_items', to='contenttypes.contenttype', verbose_name='نوع محتوا'),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_items', to='reference.reference', verbose_name='مرجع'),
        ),
    ]
