# Generated by Django 4.0.4 on 2022-04-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reference', '0005_alter_reference_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.reference'),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.reference'),
        ),
    ]
