# Generated by Django 4.0.3 on 2022-04-11 16:33

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_alter_author_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='img/r/', verbose_name='تصویر جلد'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='date_modified',
            field=django_jalali.db.models.jDateTimeField(verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.URLField(max_length=255, verbose_name='لینک دانلود'),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='آی دی آبجکت'),
        ),
    ]
