# Generated by Django 4.0.3 on 2022-04-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_alter_author_full_name_alter_reference_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسنده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'مرجع', 'verbose_name_plural': 'مراجع'},
        ),
        migrations.AlterModelOptions(
            name='referenceitem',
            options={'verbose_name': 'رابط مرجع', 'verbose_name_plural': 'رابط\u200cهای مراجع'},
        ),
    ]
