# Generated by Django 4.2.5 on 2023-10-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], verbose_name='Semester')),
                ('column', models.PositiveSmallIntegerField(verbose_name='Column')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Specialized'), (2, 'Optional'), (3, 'Basic'), (4, 'General')], null=True, verbose_name='Type')),
                ('units', models.PositiveSmallIntegerField(blank=True, choices=[], null=True, verbose_name='Units')),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_node', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Chart Node',
                'verbose_name_plural': 'Chart Nodes',
                'ordering': ('semester', 'column'),
            },
        ),
        migrations.AddConstraint(
            model_name='chartnode',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('course__isnull', True), ('type__isnull', False), ('units__isnull', False)), models.Q(('course__isnull', False), ('type__isnull', True), ('units__isnull', True)), _connector='OR'), name='linked_to_course_or_not', violation_error_message='Nodes must either be related to a course or have a value in their type and unit fields.'),
        ),
    ]
