# Generated by Django 4.2.5 on 2023-09-29 16:52

import core.helpers
import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Full Name')),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', core.models.ShortUuidField(db_index=True, default=core.helpers.uuid_generator, editable=False, max_length=11, unique=True, verbose_name='UUID')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified Time')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Book'), (2, 'Solution'), (3, 'Slide'), (4, 'Handout'), (5, 'Summary'), (6, 'Other')], verbose_name='Type')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('file', models.FileField(blank=True, null=True, upload_to='references', verbose_name='File')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/references_cover', validators=[core.validators.MaxImageSizeValidator(1)], verbose_name='Cover Image')),
                ('courses', models.ManyToManyField(blank=True, related_name='references', to='courses.course', verbose_name='Courses')),
                ('related_references', models.ManyToManyField(blank=True, to='references.reference', verbose_name='Related References')),
                ('writers', models.ManyToManyField(blank=True, related_name='references', to='references.writer', verbose_name='Writer')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'ordering': ('-modified_time', '-created_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.CheckConstraint(check=models.Q(('type__in', (1, 2)), models.Q(('title__isnull', True), ('title__exact', ''), _connector='OR'), _negated=True), name='check_books_and_solutions_have_title'),
        ),
    ]
