# Generated by Django 4.2.5 on 2023-10-02 10:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_reference_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/references_cover', validators=[core.validators.MaxImageSizeValidator(5)], verbose_name='Cover Image'),
        ),
    ]
