# Generated by Django 4.2.5 on 2024-03-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_solution',
            field=models.BooleanField(default=False, verbose_name='Is Solution?'),
        ),
    ]
